name: dnd_helper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  flutter:
    sdk: flutter
  graphql: ^5.2.3
  flutter_riverpod: ^2.6.1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  graphql_codegen: ^3.0.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
